import * as fs from 'fs';
import * as path from 'path';
import { ScanReport, Violation } from './types/index.js';

export class Reporter {
  generateMarkdown(report: ScanReport): string {
    let output = '# LaunchGuard Scan Report\n\n';
    output += `**Timestamp:** ${report.timestamp}\n`;
    output += `**Mode:** ${report.mode}\n`;
    output += `**Files Scanned:** ${report.filesScanned}\n\n`;

    output += '## Summary\n\n';
    output += `- **Status:** ${report.summary.passed ? '✅ PASS' : '❌ FAIL'}\n`;
    output += `- **Errors:** ${report.summary.errors}\n`;
    output += `- **Warnings:** ${report.summary.warnings}\n\n`;

    if (report.violations.length > 0) {
      output += '## Violations\n\n';

      // Group by file
      const byFile = this.groupByFile(report.violations);
      for (const [file, violations] of Object.entries(byFile)) {
        output += `### ${file}\n\n`;
        for (const violation of violations) {
          const icon = violation.severity === 'error' ? '❌' : '⚠️';
          output += `${icon} **${violation.ruleId}** (Line ${violation.line}:${violation.column})\n`;
          output += `   ${violation.message}\n`;
          if (violation.context) {
            output += `   \`\`\`\n   ${violation.context}\n   \`\`\`\n`;
          }
          output += '\n';
        }
      }
    }

    if (report.claimLedger.length > 0) {
      output += '## Claim Ledger (ARCHI-Ω v1.2)\n\n';
      output += 'Claims found in scanned files:\n\n';
      output += '| Claim-ID | File | Line | Tag | S-Level | Dependencies | Testability | Test Status | Claim |\n';
      output += '|----------|------|------|-----|---------|--------------|-------------|-------------|-------|\n';

      for (const claim of report.claimLedger) {
        const claimText = claim.claim
          .replace(/\\/g, '\\\\')
          .replace(/\|/g, '\\|')
          .substring(0, 60);
        const deps = claim.dependencies.length > 0 ? claim.dependencies.join(', ') : '-';
        output += `| ${claim.claimId} | ${claim.file} | ${claim.line} | ${claim.tag} | ${claim.proofLevel} | ${deps} | ${claim.testability} | ${claim.testStatus} | ${claimText} |\n`;
      }
      output += '\n';
    }

    // ARCHI-Ω v1.2: Sensitivity Map
    if (report.sensitivityMap && report.sensitivityMap.length > 0) {
      output += '## Sensitivity Map (ARCHI-Ω v1.2)\n\n';
      output += 'Top factors that would change recommendations:\n\n';
      output += '| Factor | Impact | Threshold | Test |\n';
      output += '|--------|--------|-----------|------|\n';

      for (const factor of report.sensitivityMap) {
        const impact = factor.impact.replace(/\|/g, '\\|').substring(0, 60);
        const test = factor.test.replace(/\|/g, '\\|').substring(0, 60);
        output += `| ${factor.factor} | ${impact} | ${factor.threshold} | ${test} |\n`;
      }
      output += '\n';
    }

    output += '---\n';
    output += '*Generated by LaunchGuard - Deterministic quality gate for docs*\n';

    return output;
  }

  generateConsoleOutput(report: ScanReport): string {
    let output = '\n';
    output += '═══════════════════════════════════════════════════════════\n';
    output += '  LaunchGuard Scan Results (ARCHI-Ω v1.2)\n';
    output += '═══════════════════════════════════════════════════════════\n\n';

    output += `Mode:          ${report.mode.toUpperCase()}\n`;
    output += `Files Scanned: ${report.filesScanned}\n`;
    output += `Status:        ${report.summary.passed ? '✅ PASS' : '❌ FAIL'}\n`;
    output += `Errors:        ${report.summary.errors}\n`;
    output += `Warnings:      ${report.summary.warnings}\n`;

    // ARCHI-Ω v1.2: Risk distribution
    if (report.summary.riskDistribution) {
      const rd = report.summary.riskDistribution;
      output += `\nRisk Distribution:\n`;
      if (rd.R3 > 0) output += `  ⛔ R3 (Critical):     ${rd.R3}\n`;
      if (rd.R2 > 0) output += `  🔴 R2 (High Impact):  ${rd.R2}\n`;
      if (rd.R1 > 0) output += `  🟡 R1 (Operational):  ${rd.R1}\n`;
      if (rd.R0 > 0) output += `  🟢 R0 (Low):          ${rd.R0}\n`;
    }

    if (report.violations.length > 0) {
      output += '\n───────────────────────────────────────────────────────────\n';
      output += ' Violations\n';
      output += '───────────────────────────────────────────────────────────\n\n';

      for (const violation of report.violations) {
        const icon = violation.severity === 'error' ? '❌' : '⚠️';
        output += `${icon} ${violation.file}:${violation.line}:${violation.column}\n`;
        output += `   [${violation.ruleId}] ${violation.message}\n`;
        if (violation.context) {
          output += `   ${violation.context}\n`;
        }
        output += '\n';
      }
    }

    if (report.claimLedger.length > 0 && report.claimLedger.length <= 10) {
      output += '\n───────────────────────────────────────────────────────────\n';
      output += ' Claim Ledger (ARCHI-Ω v1.2 - sample)\n';
      output += '───────────────────────────────────────────────────────────\n\n';

      for (const claim of report.claimLedger.slice(0, 10)) {
        const status = claim.testStatus === 'PASS' ? '✅' : claim.testStatus === 'FAIL' ? '❌' : '❓';
        output += `${status} [${claim.tag}] ${claim.proofLevel} (${claim.testability}) ${claim.file}:${claim.line}\n`;
        output += `  ${claim.claim.substring(0, 80)}\n`;
        if (claim.dependencies.length > 0) {
          output += `  Dependencies: ${claim.dependencies.join(', ')}\n`;
        }
        output += '\n';
      }

      if (report.claimLedger.length > 10) {
        output += `... and ${report.claimLedger.length - 10} more claims\n\n`;
      }
    }

    // ARCHI-Ω v1.2: Sensitivity Map
    if (report.sensitivityMap && report.sensitivityMap.length > 0) {
      output += '\n───────────────────────────────────────────────────────────\n';
      output += ' Sensitivity Map (ARCHI-Ω v1.2)\n';
      output += '───────────────────────────────────────────────────────────\n\n';

      for (const factor of report.sensitivityMap) {
        output += `📊 ${factor.factor}\n`;
        output += `   Impact: ${factor.impact}\n`;
        output += `   Test: ${factor.test}\n\n`;
      }
    }

    output += '═══════════════════════════════════════════════════════════\n';

    return output;
  }

  async writeReports(report: ScanReport, outputDir: string): Promise<void> {
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write JSON report
    const jsonPath = path.join(outputDir, 'report.json');
    fs.writeFileSync(jsonPath, JSON.stringify(report, null, 2), 'utf-8');

    // Write Markdown report
    const mdPath = path.join(outputDir, 'report.md');
    fs.writeFileSync(mdPath, this.generateMarkdown(report), 'utf-8');
  }

  private groupByFile(violations: Violation[]): Record<string, Violation[]> {
    const grouped: Record<string, Violation[]> = {};
    for (const violation of violations) {
      if (!grouped[violation.file]) {
        grouped[violation.file] = [];
      }
      grouped[violation.file].push(violation);
    }
    return grouped;
  }
}
